### PR TITLE
Update python_pgd.py

### PR DESCRIPTION
**Pull request by josephsalmon**
Harmonizing names according to benchmark_lasso:
PGD - >Python-PGD

### CODE REVIEW

**Comment by mathurinm** [comment]
I have mixed feelings : 
- on the one hand it's surprising to have the same solver have different names across benchmarks, and so it's nice to harmonize
- on the other hand such changes break existing config files, and  anyways we will not be able to ensure consistency across all benchmarks as more and more benchmark develop, so I'm OK with separate benchmarks not being harmonized (if you think about it, they already  aren't in some aspects : the datafit in benchmark_lasso is not normalized by n_samples, while here it is) 

What do you think @josephsalmon  @agramfort @tomMoral ?

**Comment by agramfort** [comment]
I would say we can try to converge on common name but I would not invest
too much time on this. I feel we have more important stuff to work on.

**Comment by tomMoral** [comment]
For the `Lasso` benchmark, we needed `Python-PGD` because we also have `R-pgd` and `Julia-PGD`.
I would say that in this case, as there is no cross language involve, this is not necessary.

The names do not need to be uniform as the benchmarks are independent so I am overall -0.5 on this change.

**Comment by josephsalmon** [comment]
> I have mixed feelings :
> 
>     * on the one hand it's surprising to have the same solver have different names across benchmarks, and so it's nice to harmonize
> 
>     * on the other hand such changes break existing config files, and  anyways we will not be able to ensure consistency across all benchmarks as more and more benchmark develop, so I'm OK with separate benchmarks not being harmonized (if you think about it, they already  aren't in some aspects : the datafit in benchmark_lasso is not normalized by n_samples, while here it is)

I think the issue you raised is more important, we should at least try to harmonize the normalization (1/n_samples) across benchmark we created (for the future one, hopefully they will try to mimick us...)

For the naming, it isless important indeed as @agramfort said.
But a default policy could be:
- all python codes: no mention of the langage
- all non python code : add suffix   `-<langage_naming>` accross benchmarks.

my 2cts.
> 
> 
> What do you think @josephsalmon @agramfort @tomMoral ?

**Pull request closed without merging**
